### ISSUE TITLE
Issues after upgrading to 3.1.5

### ISSUE THREAD

**Issue by sbsrouteur** [fooplugins/FooTable#733]
Since upgrading to 3.1.5, I have the following jquery exception :
Loading boat info from server....
4jquery-3.2.1.min.js:2 jQuery.Deferred exception: Cannot read property 'name' of null TypeError: Cannot read property 'name' of null
    at Class.draw (https://vlm-dev.ddns.net/jvlm/external/footable-bootstrap/js/footable.js:2803:83)
    at Object.<anonymous> (https://vlm-dev.ddns.net/jvlm/external/footable-bootstrap/js/footable.js:2295:41)
    at Function.Deferred (https://vlm-dev.ddns.net/jvlm/external/jquery/jquery-3.2.1.min.js:2:31033)
    at obj._execute (https://vlm-dev.ddns.net/jvlm/external/footable-bootstrap/js/footable.js:2293:13)
    at obj.execute (https://vlm-dev.ddns.net/jvlm/external/footable-bootstrap/js/footable.js:2269:25)
    at https://vlm-dev.ddns.net/jvlm/external/footable-bootstrap/js/footable.js:2221:18
    at j (https://vlm-dev.ddns.net/jvlm/external/jquery/jquery-3.2.1.min.js:2:29999)
    at k (https://vlm-dev.ddns.net/jvlm/external/jquery/jquery-3.2.1.min.js:2:30313) undefined

I have 2 footable inited using the myvar=Footable.init syntax. It used to work in 3.1.3.

Not sure it has side effects afterwards

**Comment by sbsrouteur** [comment]
Somehow the event handling has changed, and using the initcomplete event is not good enough. I moved my code to load the table content after ready.ft.table event and this fixed the issue.

It seems it is possible to have data get in the table between the init and ready, and it messes the table.

Maybe some doc on the .init can events constraints would help.
